name:                welford-online-mean-variance
version:             0.1.0.0
github:              "schnecki/welford-online-mean-variance"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schnecki@gmail.com"
copyright:           "2022 Manuel Schneckenreither"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Online computation of mean and variance using the Welford algorithm.
category:            Statistics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/welford-online-mean-variance#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- deepseq
- cereal

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  welford-online-mean-variance-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - welford-online-mean-variance
    - tasty
    - tasty-discover
    - tasty-quickcheck
    - QuickCheck
    - vector
